# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YTQ1NDE3MmJhNWZiZWY5MGJmYTkyOTU1NTkyNjUzODMxZmU0MGY5MDc0ZDc1NGE1ODVjYjIzOWI1Y2IwZDVhZTViNzZlOGMxMzA4MjI5MzE4NGNmYTIzNzJhMjZiZjJjOWZmOTBkYjE1YzhmZTA2YTllMjI0ZTU1NGVjY2ExMWY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
